import React from 'react';
import { Sparkles, AlertTriangle, Coins, CheckSquare, Bot } from 'lucide-react';

interface TodayBriefingProps {
  topRiskClient: string;
  expectedCash: string;
  bestAction: string;
  isLoading: boolean;
}

export const TodayBriefing: React.FC<TodayBriefingProps> = ({
  topRiskClient,
  expectedCash,
  bestAction,
  isLoading,
}) => {
  if (isLoading) {
    return (
      <div className="glow-card bg-charcoal-card rounded-[24px] p-6 space-y-4 animate-pulse border border-charcoal-border">
        <div className="h-5 bg-gray-800 rounded w-1/4"></div>
        <div className="h-20 bg-gray-800 rounded"></div>
      </div>
    );
  }

  return (
    <div className="glow-card bg-charcoal-card rounded-[24px] p-6 border border-charcoal-border relative overflow-hidden transition-all duration-300">
      {/* Decorative gradient corner */}
      <div className="absolute top-0 right-0 w-36 h-36 bg-indigo-500/10 blur-3xl rounded-full pointer-events-none" />
      
      {/* Card Header */}
      <div className="flex justify-between items-center">
        <h2 className="text-base font-bold text-white tracking-tight flex items-center gap-2">
          <Bot className="h-5 w-5 text-indigo-400" />
          Today's AI Briefing
        </h2>
        <span className="inline-flex items-center gap-1 text-[9px] font-extrabold uppercase tracking-wider bg-indigo-500/15 border border-indigo-500/30 text-indigo-300 px-2.5 py-1 rounded-full">
          <Sparkles className="h-2.5 w-2.5" /> Generated by Gemma
        </span>
      </div>

      {/* Briefing grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-6">
        
        {/* Top Risk Section */}
        <div className="p-4 bg-rose-500/[0.03] border border-rose-500/10 rounded-2xl flex gap-3.5 items-start">
          <div className="p-2 bg-rose-500/10 border border-rose-500/25 rounded-xl text-rose-400 shrink-0">
            <AlertTriangle className="h-4.5 w-4.5" />
          </div>
          <div>
            <span className="text-[10px] text-gray-500 uppercase font-semibold tracking-wider">Top Risk</span>
            <h4 className="text-sm font-extrabold text-white mt-1">{topRiskClient}</h4>
            <p className="text-[11px] text-gray-400 mt-0.5 font-medium leading-normal">
              Flagged due to chronic behavior history.
            </p>
          </div>
        </div>

        {/* Expected Cash Section */}
        <div className="p-4 bg-emerald-500/[0.03] border border-emerald-500/10 rounded-2xl flex gap-3.5 items-start">
          <div className="p-2 bg-emerald-500/10 border border-emerald-500/25 rounded-xl text-emerald-400 shrink-0">
            <Coins className="h-4.5 w-4.5" />
          </div>
          <div>
            <span className="text-[10px] text-gray-500 uppercase font-semibold tracking-wider">Expected Cash</span>
            <h4 className="text-sm font-extrabold text-white mt-1">{expectedCash}</h4>
            <p className="text-[11px] text-gray-400 mt-0.5 font-medium leading-normal">
              Based on historical clearance timelines.
            </p>
          </div>
        </div>

        {/* Best Action Section */}
        <div className="p-4 bg-indigo-500/[0.03] border border-indigo-500/10 rounded-2xl flex gap-3.5 items-start">
          <div className="p-2 bg-indigo-500/10 border border-indigo-500/25 rounded-xl text-indigo-400 shrink-0">
            <CheckSquare className="h-4.5 w-4.5" />
          </div>
          <div>
            <span className="text-[10px] text-gray-500 uppercase font-semibold tracking-wider">Best Action</span>
            <h4 className="text-sm font-extrabold text-indigo-300 mt-1">{bestAction}</h4>
            <p className="text-[11px] text-gray-400 mt-0.5 font-medium leading-normal">
              Automate notices to accelerate cash intake.
            </p>
          </div>
        </div>

      </div>
    </div>
  );
};
